M48
; DRILL file {KiCad 9.0.4} date 2025-10-29T19:38:58-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-29T19:38:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X99.3Y-115.2
T2
X93.98Y-53.34
X93.98Y-133.35
X179.07Y-53.34
X179.07Y-133.35
M30
